[package]
name                  = "oxc_inspect_ast"
version               = "0.0.0"
publish               = false
authors.workspace     = true
description.workspace = true
edition.workspace     = true
homepage.workspace    = true
keywords.workspace    = true
license.workspace     = true
repository.workspace  = true

[dependencies]
oxc_ast = { workspace = true }

layout_inspect = { workspace = true, features = ["serde", "unique_names"] }
serde_json     = { workspace = true }
