name: Benchmark

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize]
    paths:
      - '**/*.rs'
      - 'napi/parser/**/*.js'
      - 'napi/parser/**/*.mjs'
      - 'Cargo.lock'
      - '.github/workflows/benchmark.yml'
  push:
    branches:
      - main
      - bench-*
    paths:
      - '**/*.rs'
      - 'napi/parser/**/*.js'
      - 'napi/parser/**/*.mjs'
      - 'Cargo.lock'
      - '.github/workflows/benchmark.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  benchmark:
    name: Benchmark
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v4
        with:
          progress: false
          persist-credentials: false

      - name: Install Rust Toolchain
        uses: ./.github/actions/rustup
        with:
          shared-key: 'benchmark'
          save-cache: ${{ github.ref_name == 'main' }}

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org'

      - name: Build NAPI benchmark
        working-directory: ./napi/parser
        run: |
          corepack enable
          pnpm install
          pnpm run build

      - name: Run NAPI benchmark
        uses: CodSpeedHQ/action@v2
        timeout-minutes: 30
        with:
          run: node napi/parser/parse.bench.mjs
          token: ${{ secrets.CODSPEED_TOKEN }}

  benchmark-napi-uninstrumented:
    name: Benchmark NAPI uninstrumented
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v4
        with:
          progress: false
          persist-credentials: false

      - name: Install Rust Toolchain
        uses: ./.github/actions/rustup
        with:
          shared-key: 'benchmark'
          save-cache: ${{ github.ref_name == 'main' }}

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org'

      - name: Build NAPI benchmark
        working-directory: ./napi/parser
        run: |
          corepack enable
          pnpm install
          pnpm run build

      - name: Run NAPI benchmark
        run: DISABLE_CODSPEED=true node napi/parser/parse.bench.mjs
